// Code generated by tools/genlanguages from i18n/supported-languages.json. DO NOT EDIT.

export const SUPPORTED_LANGUAGES = [
  "en",
  "zh",
  "zh-TW",
  "ar",
  "fr",
  "ja",
  "hi",
  "es",
  "pt",
  "ru",
  "ko",
  "de",
] as const;

export type SupportedLanguageCode = (typeof SUPPORTED_LANGUAGES)[number];

export const DEFAULT_LANGUAGE: SupportedLanguageCode = "en";
