// Command genlanguages generates Go and TypeScript language lists from i18n/supported-languages.json.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type config struct {
	Default   string   `json:"default"`
	Languages []string `json:"languages"`
}

func main() {
	root := flag.String("root", ".", "path to pdf_wizard module root (contains i18n/supported-languages.json)")
	flag.Parse()

	cfg, err := loadConfig(filepath.Join(*root, "i18n", "supported-languages.json"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "genlanguages: %v\n", err)
		os.Exit(1)
	}

	goPath := filepath.Join(*root, "languages_gen.go")
	tsPath := filepath.Join(*root, "frontend", "src", "utils", "i18n", "languages.gen.ts")

	if err := os.WriteFile(goPath, []byte(renderGo(cfg)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genlanguages: write %s: %v\n", goPath, err)
		os.Exit(1)
	}
	if err := os.WriteFile(tsPath, []byte(renderTS(cfg)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genlanguages: write %s: %v\n", tsPath, err)
		os.Exit(1)
	}

	fmt.Printf("genlanguages: wrote %s and %s (%d languages)\n", goPath, tsPath, len(cfg.Languages))
}

func loadConfig(path string) (*config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	if len(cfg.Languages) == 0 {
		return nil, fmt.Errorf("languages list is empty")
	}
	seen := make(map[string]bool, len(cfg.Languages))
	for _, code := range cfg.Languages {
		code = strings.TrimSpace(code)
		if code == "" {
			return nil, fmt.Errorf("language code cannot be empty")
		}
		if seen[code] {
			return nil, fmt.Errorf("duplicate language code: %s", code)
		}
		seen[code] = true
	}
	if strings.TrimSpace(cfg.Default) == "" {
		return nil, fmt.Errorf("default language is required")
	}
	if !seen[cfg.Default] {
		return nil, fmt.Errorf("default language %q is not in languages list", cfg.Default)
	}
	return &cfg, nil
}

func renderGo(cfg *config) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/genlanguages from i18n/supported-languages.json. DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("// SupportedLanguageCodes is the ordered list of locale codes (source: i18n/supported-languages.json).\n")
	b.WriteString("var SupportedLanguageCodes = []string{\n")
	for _, code := range cfg.Languages {
		fmt.Fprintf(&b, "\t%q,\n", code)
	}
	b.WriteString("}\n\n")
	b.WriteString("// validLanguages is populated from SupportedLanguageCodes.\n")
	b.WriteString("var validLanguages = map[string]bool{\n")
	for _, code := range cfg.Languages {
		fmt.Fprintf(&b, "\t%q: true,\n", code)
	}
	b.WriteString("}\n")
	return b.String()
}

func renderTS(cfg *config) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/genlanguages from i18n/supported-languages.json. DO NOT EDIT.\n\n")
	b.WriteString("export const SUPPORTED_LANGUAGES = [\n")
	for _, code := range cfg.Languages {
		fmt.Fprintf(&b, "  %q,\n", code)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type SupportedLanguageCode = (typeof SUPPORTED_LANGUAGES)[number];\n\n")
	fmt.Fprintf(&b, "export const DEFAULT_LANGUAGE: SupportedLanguageCode = %q;\n", cfg.Default)
	return b.String()
}
