// Code generated by tools/genlanguages from i18n/supported-languages.json. DO NOT EDIT.

package main

// SupportedLanguageCodes is the ordered list of locale codes (source: i18n/supported-languages.json).
var SupportedLanguageCodes = []string{
	"en",
	"zh",
	"zh-TW",
	"ar",
	"fr",
	"ja",
	"hi",
	"es",
	"pt",
	"ru",
	"ko",
	"de",
}

// validLanguages is populated from SupportedLanguageCodes.
var validLanguages = map[string]bool{
	"en": true,
	"zh": true,
	"zh-TW": true,
	"ar": true,
	"fr": true,
	"ja": true,
	"hi": true,
	"es": true,
	"pt": true,
	"ru": true,
	"ko": true,
	"de": true,
}
