// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyWatermark(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyWatermark'](arg1, arg2, arg3, arg4);
}

export function EmitSettingsEvent() {
  return window['go']['main']['App']['EmitSettingsEvent']();
}

export function GetFileMetadata(arg1) {
  return window['go']['main']['App']['GetFileMetadata'](arg1);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetPDFMetadata(arg1) {
  return window['go']['main']['App']['GetPDFMetadata'](arg1);
}

export function GetPDFPageCount(arg1) {
  return window['go']['main']['App']['GetPDFPageCount'](arg1);
}

export function MergePDFs(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergePDFs'](arg1, arg2, arg3);
}

export function RotatePDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RotatePDF'](arg1, arg2, arg3, arg4);
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function SelectPDFFile() {
  return window['go']['main']['App']['SelectPDFFile']();
}

export function SelectPDFFiles() {
  return window['go']['main']['App']['SelectPDFFiles']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SplitPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitPDF'](arg1, arg2, arg3);
}
