// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyWatermark(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyWatermark'](arg1, arg2, arg3, arg4);
}

export function CancelCurrentOperation() {
  return window['go']['main']['App']['CancelCurrentOperation']();
}

export function EmitSettingsEvent() {
  return window['go']['main']['App']['EmitSettingsEvent']();
}

export function ExtractPDFText(arg1) {
  return window['go']['main']['App']['ExtractPDFText'](arg1);
}

export function GetFileMetadata(arg1) {
  return window['go']['main']['App']['GetFileMetadata'](arg1);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetPDFMetadata(arg1) {
  return window['go']['main']['App']['GetPDFMetadata'](arg1);
}

export function GetPDFPageCount(arg1) {
  return window['go']['main']['App']['GetPDFPageCount'](arg1);
}

export function ImagesToPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImagesToPDF'](arg1, arg2, arg3);
}

export function LockPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LockPDF'](arg1, arg2, arg3, arg4);
}

export function MergePDFs(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergePDFs'](arg1, arg2, arg3);
}

export function RotatePDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RotatePDF'](arg1, arg2, arg3, arg4);
}

export function SelectImageFiles(arg1) {
  return window['go']['main']['App']['SelectImageFiles'](arg1);
}

export function SelectOutputDirectory(arg1) {
  return window['go']['main']['App']['SelectOutputDirectory'](arg1);
}

export function SelectPDFFile(arg1) {
  return window['go']['main']['App']['SelectPDFFile'](arg1);
}

export function SelectPDFFiles(arg1) {
  return window['go']['main']['App']['SelectPDFFiles'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SplitPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitPDF'](arg1, arg2, arg3);
}

export function StartImagesPhoneUpload(arg1) {
  return window['go']['main']['App']['StartImagesPhoneUpload'](arg1);
}

export function StopImagesPhoneUpload() {
  return window['go']['main']['App']['StopImagesPhoneUpload']();
}

export function UnlockPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UnlockPDF'](arg1, arg2, arg3, arg4);
}
