// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFileMetadata(arg1:string):Promise<main.PDFMetadata>;

export function GetPDFMetadata(arg1:string):Promise<main.PDFMetadata>;

export function GetPDFPageCount(arg1:string):Promise<number>;

export function MergePDFs(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function SelectOutputDirectory():Promise<string>;

export function SelectPDFFile():Promise<string>;

export function SelectPDFFiles():Promise<Array<string>>;

export function SplitPDF(arg1:string,arg2:Array<main.SplitDefinition>,arg3:string):Promise<void>;
