// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ApplyWatermark(arg1:string,arg2:models.WatermarkDefinition,arg3:string,arg4:string):Promise<void>;

export function EmitSettingsEvent():Promise<void>;

export function ExtractPDFText(arg1:string):Promise<string>;

export function FillPDFForm(arg1:string,arg2:Array<models.PDFFormFieldValue>,arg3:string,arg4:string):Promise<void>;

export function GetFileMetadata(arg1:string):Promise<models.PDFMetadata>;

export function GetLanguage():Promise<string>;

export function GetPDFMetadata(arg1:string):Promise<models.PDFMetadata>;

export function GetPDFPageCount(arg1:string):Promise<number>;

export function ImagesToPDF(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function ListPDFFormFields(arg1:string):Promise<Array<models.PDFFormField>>;

export function LockPDF(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MergePDFs(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function RotatePDF(arg1:string,arg2:Array<models.RotateDefinition>,arg3:string,arg4:string):Promise<void>;

export function SelectImageFiles(arg1:models.FileDialogLabels):Promise<Array<string>>;

export function SelectOutputDirectory(arg1:models.FileDialogLabels):Promise<string>;

export function SelectPDFFile(arg1:models.FileDialogLabels):Promise<string>;

export function SelectPDFFiles(arg1:models.FileDialogLabels):Promise<Array<string>>;

export function SetLanguage(arg1:string):Promise<void>;

export function SplitPDF(arg1:string,arg2:Array<models.SplitDefinition>,arg3:string):Promise<void>;

export function StartImagesPhoneUpload(arg1:models.PhoneUploadPageCopy):Promise<string>;

export function StopImagesPhoneUpload():Promise<void>;

export function UnlockPDF(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
