// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function EmitSettingsEvent():Promise<void>;

export function GetFileMetadata(arg1:string):Promise<models.PDFMetadata>;

export function GetLanguage():Promise<string>;

export function GetPDFMetadata(arg1:string):Promise<models.PDFMetadata>;

export function GetPDFPageCount(arg1:string):Promise<number>;

export function MergePDFs(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function RotatePDF(arg1:string,arg2:Array<models.RotateDefinition>,arg3:string,arg4:string):Promise<void>;

export function SelectOutputDirectory():Promise<string>;

export function SelectPDFFile():Promise<string>;

export function SelectPDFFiles():Promise<Array<string>>;

export function SetLanguage(arg1:string):Promise<void>;

export function SplitPDF(arg1:string,arg2:Array<models.SplitDefinition>,arg3:string):Promise<void>;
